root: /work/n02/n02/sdat2/adcirc-swan/
exe_path: /work/n02/n02/sdat2/adcirc-swan/adcirc/work # path to the adcirc executables
exp_path: /work/n02/n02/sdat2/adcirc-swan/exp # path to the expeiriment directory
run_folder: "" # folder to run the model in
low_storage: false # deletes unncessary files