root: /work/n01/n01/sithom/adcirc-swan/ #/work/n02/n02/sdat2/adcirc-swan/
exe_path: /work/n01/n01/sithom/adcirc-swan/adcirc/work #/work/n02/n02/sdat2/adcirc-swan/adcirc/work # path to the adcirc executables
exp_path: /work/n01/n01/sithom/adcirc-swan/exp #/work/n02/n02/sdat2/adcirc-swan/exp # path to the expeiriment directory
run_folder: "" # folder to run the model in
low_storage: false # deletes unncessary files (fort.22.nc input file) after run finished