root: /work/n01/n01/sithom/adcirc-swan/
exe_path: /work/n01/n01/sithom/adcirc-swan/tcpips/work # path to the adcirc executables
exp_path: /work/n01/n01/sithom/adcirc-swan/adcirc/exp/ # path to the expeiriment directory
run_folder: "" # folder to run the model in
low_storage: false # deletes unncessary files (fort.22.nc input file) after run finished
