email: sdat2@cam.ac.uk
partition: standard
slurm_account: n02-bas
slurm_job_name: adcirc-swan
root: "/work/n02/n02/sdat2/adcirc-swan/"
exe_path: "/work/n02/n02/sdat2/adcirc-swan/adcirc/work"
tasks_per_node: 128
options:
  high:
    nodes: 8
    qos: "standard"
    walltime: "01:00:00"
  mid:
    nodes: 4
    qos: "short"
    walltime: "00:20:00"
  low:
    nodes: 2
    qos: "short"
    walltime: "00:20:00"
modules:
 - PrgEnv-gnu/8.3.3 cray-hdf5-parallel/1.12.2.1
 - cray-netcdf-hdf5parallel/4.9.0.1
input_files:
  - fort.13
  - fort.14
  - fort.15
