# a config file for the wrap function in the worstsurge.adforce module
# Should contain the default values for a TC
angle:
  value: 0
  description: "Bearing of the TC track in degrees from true north"
  units: "degrees"
translation_speed:
  value: 7.71
  description: "Speed of the TC in the direction of the track"
  units: "m/s"
profile_name:
  value: "2025"
  description: "Name of the wind and pressure profile to use"
impact_location:
  value: 
   - -89.4715
   -  29.5111
  description: "Location of the TC center at the time of landfall (x, y)"
  units: "degrees"
impact_time: # roughly the same as Katrina by default
  value: "2005-08-29T06:10:00"
  description: "Time of landfall"
observation_location:
  value: [-90.0715, 29.9511] # default New Orleans location
  type: list
  description: "Location of the observation point (x, y). Will pick the closest mesh node to this."
  units: "degrees"
setup:
  value: "mid"
  type: str
  units: "dimensionless"
  description: "Configuration of the model"
  options: ["low", "mid", "high"]
tide:
  value: false
  type: float
  description: "Whether to turn tides on"
  units: "dimensionless"
