defaults:
  - slurm: slurm_config
  - tc: tc_param_config
  - grid: grid_fort22_config
  - adcirc: adcirc_config
  - files: n01_archer2_config
  - _self_

name: test-wrap
use_slurm: false # avoid launching additional slurm jobs by default.
ani: false