Main: # main stationary grid
  type: rectilinear_square # type parameters not currently used
  bottom_left_corner: 
    - -99.0
    - 0.0
  lateral_spacing: 0.125
  xlen: 393
  ylen: 385
  tlen: 673
  start: 2005-08-25T00:00:00 # 7680900 # number of minutes since 1990-01-01T01:00:00 (should change to datetime format?) '%Y-%m-%dT%H:%M:%S'
  timestep: 15 # minutes
  time_unit: minutes since 1990-01-01T01:00:00
  time_calendar: proleptic_gregorian
TC1: # tropical cylone moves with the center of the grid
  type: moving_rectilinear_square 
  lateral_spacing: 0.0125 # 1/10 of the spacing of the main grid
  xlen: 161
  ylen: 161
  tlen: 673 # 7.01 days, was 481 (5.01 days)
  start: 2005-08-25T00:00:00 # 7680900
  timestep: 15 # minutes
  time_unit: minutes since 1990-01-01T01:00:00
  time_calendar: proleptic_gregorian