# a config file for the wrap function in the worstsurge.adforce module
# Should contain the default values for a TC
angle:
  value: 0
  description: "Bearing of the TC track in degrees (clockwise) from true north"
  units: "degrees"
translation_speed:
  value: 7.71
  description: "Speed of the TC in the direction of the track"
  units: "m/s"
profile_name:
  value: "2025"
  description: "Name of the wind and pressure profile to use. Looks by default in the cle/data directory for a json with the name <profile_name.value>.json"
  units: "dimensionless"
profile_path:
  value: "/work/n02/n02/sdat2/adcirc-swan/cle/data"
  description: "Path to the directory containing the wind and pressure profiles"
  units: "dimensionless"
impact_location:
  value: 
   - -89.4715
   -  29.5111
  description: "Location of the TC center at the time of landfall (x, y)"
  units: "degrees"
impact_time: # roughly the same as Katrina by default
  value: 2005-08-12T06:00:00
  description: Time of landfall