# a config file for the wrap function in the worstsurge.adforce module
# Should contain the default values for a TC
angle:
  value: 0
  description: "Bearing of the TC track in degrees (clockwise) from true north"
  units: "degrees"
translation_speed:
  value: 7.71
  description: "Speed of the TC in the direction of the track"
  units: "m/s"
profile_name:
  value: "2015_new_orleans_profile_r4i1p1f1"
  description: "Name of the wind and pressure profile to use. Looks by default in the cle/data directory for a json with the name <profile_name.value>.json"
  units: "dimensionless"
profile_path:
  value: "/work/n01/n01/sithom/adcirc-swan/tcpips/w22/data"
  description: "Path to the directory containing the wind and pressure profiles this isn't really used by anything"
  units: "dimensionless"
impact_location:
  value: 
   - -89.4715
   -  29.5111
  description: "Location of the TC center at the time of landfall (x, y)"
  units: "degrees"
impact_time: # roughly the same as Katrina by default
  value: 2005-08-29T06:00:00
  description: Time of landfall
v_reduc:
  value: 0.8
  description: "Reduction factor for the wind speed from gradient wind to 10m height"
  units: "dimensionless"