name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Conda Environment with Mamba 🐍
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: environment.yml
        auto-update-conda: true
        use-mamba: true               # Use the fast Mamba solver
        cache-environment: true       # Cache the solved environment

    - name: Run Tests with Pytest
      # Use a conda-aware shell to ensure the test runs in the activated environment
      shell: bash -l {0}
      run: |
        pytest -W ignore::DeprecationWarning