z_star: 7
ns: 50
gamma_range:
  min: -0.4
  max: -0.1
  steps: 6
beta_range:
  min: 0.2
  max: 1.5
  steps: 6
seed: 35
quantiles:
  - 0.01
  - 0.002
seed_steps_Nr: 600
reload: true
figure:
  lp: 0.01
  up: 0.99